=== ibrahimahmed-aurea/IMI_WMS/dotnet/install/Redistributables/Reports/XSD/LoadingList.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!-- =========================================================== 
     THIS FILE IS GENERATED AUTOMATICALLY BY THE REPORT MANAGER! 
     PLEASE REFRAIN FROM EDITING SINCE IT WILL BE OVERWRITTEN!   
     =========================================================== -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="LoadingListReport">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="MetaData" type="MetaDataType"/>
				<xs:element name="Data" type="DataType"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="MetaDataType">
		<xs:attribute name="documentType" use="required"/>
		<xs:attribute name="documentSubType" use="required"/>
		<xs:attribute name="applicationIdentity" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:maxLength value="35"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="terminalIdentity" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:maxLength value="35"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="printerIdentity" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:maxLength value="35"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="userIdentity" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:maxLength value="8"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="numberOfCopies" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:byte">
					<xs:totalDigits value="5"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="isCopy" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:boolean"/>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="DataType">
		<xs:sequence>
			<xs:element name="LoadingList" type="LoadingListType" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="LoadingListType">
		<xs:sequence>
			<xs:element name="Departure" type="DepartureType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="DepartureType">
		<xs:sequence>
			<xs:element name="LoadCarrier" type="LoadCarrierType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="ShipToParty" type="ShipToPartyType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="ProductTransportType" type="ProductTransportTypeType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="DepartureId" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:maxLength value="35"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="PlannedDepartureTime" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:dateTime"/>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="RouteId" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:maxLength value="17"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="RouteDescription" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:maxLength value="35"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="WarehouseName" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:maxLength value="25"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="LoadCarrierType">
		<xs:attribute name="StopSequence" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:integer">
					<xs:totalDigits value="5"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="PartyIdentity" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:maxLength value="35"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="LoadCarrierIdentity" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:maxLength value="35"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="LoadCarrierTypeDescription" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:maxLength value="35"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="TotalWeight" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:decimal">
					<xs:totalDigits value="16"/>
					<xs:fractionDigits value="6"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="TotalVolume" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:decimal">
					<xs:totalDigits value="19"/>
					<xs:fractionDigits value="9"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="ShipAreaIdentity" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:maxLength value="3"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="ShipLocationAddress" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:maxLength value="12"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="AreaIdentity" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:maxLength value="3"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="LocationAddress" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:maxLength value="12"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="ProductTransportTypeText" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:maxLength value="35"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="ParentLoadCarrierIdentity" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:maxLength value="35"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="Name" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:maxLength value="35"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="Address" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:maxLength value="35"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="Address2" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:maxLength value="35"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="ZipCode" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:maxLength value="12"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="City" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:maxLength value="35"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="Phone" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:maxLength value="35"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="EstimatedArrivalTime" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:dateTime"/>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="ShipToPartyType">
		<xs:attribute name="DepartureIdentity" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:maxLength value="35"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="ShipToPartyIdentity" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:maxLength value="35"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="ProductTransportTypeType">
		<xs:attribute name="ProductTransportTypeIdentity" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:maxLength value="5"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="ParentLoadCarrierIdentity" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:maxLength value="35"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="ProductTransportTypeText" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:maxLength value="35"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="ShipAreaIdentity" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:maxLength value="3"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="ShipLocationAddress" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:maxLength value="12"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="TotalVolume" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:decimal">
					<xs:totalDigits value="19"/>
					<xs:fractionDigits value="9"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="TotalWeight" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:decimal">
					<xs:totalDigits value="16"/>
					<xs:fractionDigits value="6"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
</xs:schema>

=== ibrahimahmed-aurea/IMI_WMS/dotnet/install/Redistributables/Reports/test/LoadingList2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2008 sp1 (http://www.altova.com)-->
<LoadingListReport xsi:noNamespaceSchemaLocation="LoadingList.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<MetaData terminalIdentity="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" documentType="text" numberOfCopies="127" documentSubType="text" userIdentity="aaaaaaaa" applicationIdentity="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" printerIdentity="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" isCopy="true"/>
	<Data>
		<LoadingList>
			<Departure WarehouseName="aaaaaaaaaaaaaaaaaaaaaaaaa" RouteId="aaaaaaaaaaaaaaaaa" DepartureId="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" RouteDescription="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" PlannedDepartureTime="2001-12-17T09:30:47.0Z">
				<LoadCarrier ShipLocationAddress="aaaaaaaaaaaa" Address2="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" AreaIdentity="aaa" LocationAddress="aaaaaaaaaaaa" TotalVolume="1234567891.123456" Phone="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" LoadCarrierTypeDescription="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" ShipAreaIdentity="aaa" City="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" Address="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" Name="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" LoadCarrierIdentity="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" PartyIdentity="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" ZipCode="aaaaaaaaaaaa" TotalWeight="1234567891.123456" StopSequence="12345" EstimatedArrivalTime="2001-12-17T09:30:47.0Z" ProductTransportTypeText="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" ParentLoadCarrierIdentity="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"/>
				<LoadCarrier ShipLocationAddress="aaaaaaaaaaaa" Address2="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" AreaIdentity="aaa" LocationAddress="aaaaaaaaaaaa" TotalVolume="1234567891.123456" Phone="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" LoadCarrierTypeDescription="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" ShipAreaIdentity="aaa" City="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" Address="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" Name="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" LoadCarrierIdentity="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" PartyIdentity="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" ZipCode="aaaaaaaaaaaa" TotalWeight="1234567891.123456" StopSequence="12345" EstimatedArrivalTime="2001-12-17T09:30:47.0Z" ProductTransportTypeText="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" ParentLoadCarrierIdentity="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"/>
				<LoadCarrier ShipLocationAddress="aaaaaaaaaaaa" Address2="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" AreaIdentity="aaa" LocationAddress="aaaaaaaaaaaa" TotalVolume="1234567891.123456" Phone="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" LoadCarrierTypeDescription="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" ShipAreaIdentity="aaa" City="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" Address="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" Name="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" LoadCarrierIdentity="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" PartyIdentity="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" ZipCode="aaaaaaaaaaaa" TotalWeight="1234567891.123456" StopSequence="12345" EstimatedArrivalTime="2001-12-17T09:30:47.0Z" ProductTransportTypeText="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" ParentLoadCarrierIdentity="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"/>
				<LoadCarrier ShipLocationAddress="aaaaaaaaaaaa" Address2="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" AreaIdentity="aaa" LocationAddress="aaaaaaaaaaaa" TotalVolume="1234567891.123456" Phone="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" LoadCarrierTypeDescription="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" ShipAreaIdentity="aaa" City="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" Address="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" Name="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" LoadCarrierIdentity="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" PartyIdentity="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" ZipCode="aaaaaaaaaaaa" TotalWeight="1234567891.123456" StopSequence="12345" EstimatedArrivalTime="2001-12-17T09:30:47.0Z" ProductTransportTypeText="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" ParentLoadCarrierIdentity="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"/>
				<LoadCarrier ShipLocationAddress="aaaaaaaaaaaa" Address2="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" AreaIdentity="aaa" LocationAddress="aaaaaaaaaaaa" TotalVolume="1234567891.123456" Phone="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" LoadCarrierTypeDescription="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" ShipAreaIdentity="aaa" City="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" Address="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" Name="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" LoadCarrierIdentity="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" PartyIdentity="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" ZipCode="aaaaaaaaaaaa" TotalWeight="1234567891.123456" StopSequence="12345" EstimatedArrivalTime="2001-12-17T09:30:47.0Z" ProductTransportTypeText="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" ParentLoadCarrierIdentity="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"/>
				<LoadCarrier ShipLocationAddress="aaaaaaaaaaaa" Address2="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" AreaIdentity="aaa" LocationAddress="aaaaaaaaaaaa" TotalVolume="1234567891.123456" Phone="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" LoadCarrierTypeDescription="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" ShipAreaIdentity="aaa" City="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" Address="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" Name="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" LoadCarrierIdentity="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" PartyIdentity="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" ZipCode="aaaaaaaaaaaa" TotalWeight="1234567891.123456" StopSequence="12345" EstimatedArrivalTime="2001-12-17T09:30:47.0Z" ProductTransportTypeText="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" ParentLoadCarrierIdentity="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"/>
				<LoadCarrier ShipLocationAddress="aaaaaaaaaaaa" Address2="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" AreaIdentity="aaa" LocationAddress="aaaaaaaaaaaa" TotalVolume="1234567891.123456" Phone="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" LoadCarrierTypeDescription="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" ShipAreaIdentity="aaa" City="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" Address="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" Name="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" LoadCarrierIdentity="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" PartyIdentity="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" ZipCode="aaaaaaaaaaaa" TotalWeight="1234567891.123456" StopSequence="12345" EstimatedArrivalTime="2001-12-17T09:30:47.0Z" ProductTransportTypeText="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" ParentLoadCarrierIdentity="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"/>
				<LoadCarrier ShipLocationAddress="aaaaaaaaaaaa" Address2="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" AreaIdentity="aaa" LocationAddress="aaaaaaaaaaaa" TotalVolume="1234567891.123456" Phone="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" LoadCarrierTypeDescription="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" ShipAreaIdentity="aaa" City="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" Address="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" Name="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" LoadCarrierIdentity="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" PartyIdentity="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" ZipCode="aaaaaaaaaaaa" TotalWeight="1234567891.123456" StopSequence="12345" EstimatedArrivalTime="2001-12-17T09:30:47.0Z" ProductTransportTypeText="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" ParentLoadCarrierIdentity="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"/>
				<LoadCarrier ShipLocationAddress="aaaaaaaaaaaa" Address2="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" AreaIdentity="aaa" LocationAddress="aaaaaaaaaaaa" TotalVolume="1234567891.123456" Phone="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" LoadCarrierTypeDescription="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" ShipAreaIdentity="aaa" City="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" Address="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" Name="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" LoadCarrierIdentity="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" PartyIdentity="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" ZipCode="aaaaaaaaaaaa" TotalWeight="1234567891.123456" StopSequence="12345" EstimatedArrivalTime="2001-12-17T09:30:47.0Z" ProductTransportTypeText="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" ParentLoadCarrierIdentity="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"/>
				<LoadCarrier ShipLocationAddress="aaaaaaaaaaaa" Address2="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" AreaIdentity="aaa" LocationAddress="aaaaaaaaaaaa" TotalVolume="1234567891.123456" Phone="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" LoadCarrierTypeDescription="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" ShipAreaIdentity="aaa" City="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" Address="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" Name="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" LoadCarrierIdentity="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" PartyIdentity="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" ZipCode="aaaaaaaaaaaa" TotalWeight="1234567891.123456" StopSequence="12345" EstimatedArrivalTime="2001-12-17T09:30:47.0Z" ProductTransportTypeText="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" ParentLoadCarrierIdentity="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"/>
				<ShipToParty ShipToPartyIdentity="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" DepartureIdentity="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"/>
				<ShipToParty ShipToPartyIdentity="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" DepartureIdentity="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"/>
				<ShipToParty ShipToPartyIdentity="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" DepartureIdentity="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"/>
				<ShipToParty ShipToPartyIdentity="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" DepartureIdentity="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"/>
				<ShipToParty ShipToPartyIdentity="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" DepartureIdentity="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"/>
				<ShipToParty ShipToPartyIdentity="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" DepartureIdentity="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"/>
				<ShipToParty ShipToPartyIdentity="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" DepartureIdentity="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"/>
				<ShipToParty ShipToPartyIdentity="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" DepartureIdentity="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"/>
