=== ibrahimahmed-aurea/IMI_WMS/dotnet/source/CodeGenerators/Xml/xsd/StructureDescription.xsd
<?xml version="1.0" encoding="UTF-8"?><!-- edited with XMLSPY v2004 rel. 3 U (http://www.xmlspy.com) by Mats Nordgren (IMI) --><!--W3C Schema generated by XMLSPY v2004 rel. 3 U (http://www.xmlspy.com)--><xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">	<xs:include schemaLocation="Package.xsd"/>	<xs:complexType name="ModificationType">		<xs:sequence>			<xs:element name="comment" type="CommentType"/>		</xs:sequence>		<xs:attribute name="name" type="xs:string" use="required"/>		<xs:attribute name="exclude" type="xs:boolean" use="required"/>		<xs:attribute name="overrideName" type="xs:string" use="required"/>	</xs:complexType>	<xs:complexType name="ChildType">		<xs:attribute name="name" type="xs:string" use="required"/>		<xs:attribute name="minOccurrs" type="xs:integer" use="required"/>		<xs:attribute name="maxOccurrs" type="xs:string" use="required"/>	</xs:complexType>	<xs:complexType name="ModificationsType">		<xs:sequence>			<xs:element name="modification" type="ModificationType" minOccurs="0" maxOccurs="unbounded"/>		</xs:sequence>	</xs:complexType>	<xs:complexType name="ChildrenType">		<xs:sequence>			<xs:element name="child" type="ChildType" minOccurs="0" maxOccurs="unbounded"/>		</xs:sequence>	</xs:complexType>	<xs:complexType name="StructureType">		<xs:sequence>			<xs:element name="comment" type="CommentType"/>			<xs:element name="children" type="ChildrenType" minOccurs="0"/>			<xs:element name="modifications" type="ModificationsType" minOccurs="0"/>		</xs:sequence>		<xs:attribute name="name" type="xs:string" use="required"/>		<xs:attribute name="queueTable" type="xs:string" use="required"/>		<xs:attribute name="insertSP" type="xs:string" use="required"/>		<xs:attribute name="updateSP" type="xs:string" use="required"/>		<xs:attribute name="deleteSP" type="xs:string" use="required"/>		<xs:attribute name="baseTable" type="xs:string" use="required"/>	</xs:complexType>	<xs:complexType name="InterfaceType">		<xs:attribute name="name" type="xs:string" use="required"/>		<xs:attribute name="structure" type="xs:string" use="required"/>		<xs:attribute name="HAPIObjectName" type="xs:string" use="required"/>		<xs:attribute name="direction" use="required">			<xs:simpleType>				<xs:restriction base="xs:NMTOKEN">					<xs:enumeration value="In"/>					<xs:enumeration value="InOut"/>					<xs:enumeration value="Out"/>				</xs:restriction>			</xs:simpleType>		</xs:attribute>	</xs:complexType>	<xs:complexType name="StructuresType">		<xs:sequence>			<xs:element name="structure" type="StructureType" maxOccurs="unbounded"/>		</xs:sequence>	</xs:complexType>	<xs:complexType name="InterfacesType">		<xs:sequence>			<xs:element name="interface" type="InterfaceType" maxOccurs="unbounded"/>		</xs:sequence>	</xs:complexType>	<xs:element name="MessageDefinition">		<xs:complexType>			<xs:sequence>				<xs:element name="globalParameters" type="ParametersType" minOccurs="0"/>				<xs:element name="interfaces" type="InterfacesType"/>				<xs:element name="structures" type="StructuresType"/>			</xs:sequence>			<xs:attribute name="name" type="xs:string" use="required"/>			<xs:attribute name="version" type="xs:string" use="optional" default="1.0.0.0"/>		</xs:complexType>	</xs:element></xs:schema>

=== ibrahimahmed-aurea/IMI_WMS/dotnet/source/CodeGenerators/Xml/structure/TAPIOSInboundMaster.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v2004 rel. 3 U (http://www.xmlspy.com) by Mats Nordgren (IMI) -->
<!--Sample XML file generated by XMLSPY v2004 rel. 3 U (http://www.xmlspy.com)-->
<MessageDefinition xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\xsd\StructureDescription.xsd" name="InBound" version="1.0.0.0">
	<interfaces>
		<interface name="Order" structure="Order" HAPIObjectName="1" direction="In"/>
		<interface name="Node_Party" structure="Node_Party" HAPIObjectName="2" direction="In"/>
	</interfaces>
	<structures>
		<structure name="Order" insertSP="TAPI_OS.New_Order" updateSP="TAPI_OS.Modify_Order" deleteSP="TAPI_OS.Remove_Order" queueTable="" baseTable="">
			<comment>
				<line>Order</line>
			</comment>
		</structure>
		<structure name="Node_Party" insertSP="TAPI_OS.New_Modify_Node_Party" updateSP="TAPI_OS.New_Modify_Node_Party" deleteSP="TAPI_OS.Remove_Node_Party" queueTable="" baseTable="">
			<comment>
				<line>Node Party</line>
			</comment>
		</structure>
	</structures>
</MessageDefinition>
